Revert change about enabling -ftrivial-auto-var-init=zero by default
Enabling it by default caused a strange linker error when compiling LLD for ARM:

ld: ../../lib/libLLVMDebugInfoPDB.a(NativeFunctionSymbol.cpp.o): in function `llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA(unsigned long long) const [clone .localalias]':
NativeFunctionSymbol.cpp:(.text._ZNK4llvm3pdb20NativeFunctionSymbol20findInlineFramesByVAEy+0x59c): undefined reference to `.L1594'
ld: ../../lib/libLLVMDebugInfoPDB.a(NativeFunctionSymbol.cpp.o): relocation R_ARM_REL32 against external or undefined symbol `.L1594' can not be used when making a PIE executable; recompile with -fPIC
NativeFunctionSymbol.cpp:(.text._ZNK4llvm3pdb20NativeFunctionSymbol20findInlineFramesByVAEy+0x59c): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status

Although the error is only reproducible when targeting ARM platforms, better to be safe and remove the flag from the other architecture targets as well.