Fix regression on some older 32-bit architectures missing math functions
/tmp/llvm-project-llvmorg-20.1.0-rc2/llvm/lib/Support/BalancedPartitioning.cpp: In constructor 'llvm::BalancedPartitioning::BalancedPartitioning(const llvm::BalancedPartitioningConfig&)':
/tmp/llvm-project-llvmorg-20.1.0-rc2/llvm/lib/Support/BalancedPartitioning.cpp:76:25: error: 'log2' is not a member of 'std'; did you mean 'log'?
   76 |     Log2Cache[I] = std::log2(I);
      |                         ^~~~
      |                         log
[  2%] Building AVRGenCallingConv.inc...
/tmp/llvm-project-llvmorg-20.1.0-rc2/llvm/lib/Support/BalancedPartitioning.cpp: In member function 'float llvm::BalancedPartitioning::log2Cached(unsigned int) const':
/tmp/llvm-project-llvmorg-20.1.0-rc2/llvm/lib/Support/BalancedPartitioning.cpp:333:53: error: 'log2' is not a member of 'std'; did you mean 'log'?
  333 |   return (i < LOG_CACHE_SIZE) ? Log2Cache[i] : std::log2(i);
      |                                                     ^~~~
      |                                                     log