Link with -lgcc_n when cross-compiling with OBGGCC_STL_VERSION
Some GCC optimizations and floating-point operations generate calls to routines inside libgcc. However, certain symbols may be missing in older GCC runtimes, resulting in linker errors like these:

Using __bf16 on AArch64:

ld.bfd: /tmp/ccE0nWMP.o: in function `main':
conftest.c:(.text.startup+0x40): undefined reference to `__truncdfbf2'
collect2: error: ld returned 1 exit status

Compiling with -O2 or higher on i386:

ld.bfd: /tmp/ccE0nWMP.o: in function `main':
conftest.c:(.text.startup+0x40): undefined reference to `__divmoddi4'
collect2: error: ld returned 1 exit status

We cannot add new symbols to older runtimes, but we can have GCC look for the missing routines in the modern libgcc.a library it built.